### ISSUE TITLE
OnUploadCompleteAsync Call on already uploaded file upload attempt

### ISSUE THREAD

**Issue by uoziod** [smatsson/tusdotnet#17] opened 2017-05-08 14:35 UTC
OnUploadCompleteAsync is firing once upload is done, although it doesn't when it's done for already uploaded files. Is there any way to make it calling in such situations as well?

**Comment by smatsson** [comment] 2017-05-09 06:01
I'm sorry but I don't quite understand what you are asking. Do you wish to re-run the OnUploadCompleteAsync method for files that were uploaded before the callback was added?

**Comment by uoziod** [comment] 2017-05-09 07:23
Well, tus can continue interrupted uploads, right? And when you're trying to upload file that was already uploaded fully earlier, in such case callback is not firing.

**Comment by smatsson** [comment] 2017-05-09 10:59
Yes that is by design. OnUploadCompleteAsync is only fired once the first time the file is completed. This is because one would usually add processing of the file in the callback which should not run twice.

What is your use case where you wish to upload the same file multiple times?

**Comment by smatsson** [comment] 2017-05-23 19:49
@uoziod Any update on the use case or should I close this issue?

**Closed** 2017-05-24 09:44 UTC

**Comment by chris03** [comment] 2020-05-20 17:32
Simple use case would be that the background processing failed.
Say the backend service was unavailable at the time.

The user would re-upload the same file to start the process again.
The nice thing is that since the file is already on the server, the upload is skipped.. but nothing more happens.
We would need an event to inform that an user just uploaded a file.
Then we could check if we need to restart the background processing or whatever...

It's kind of strange that the user's action (uploading a file) is swallowed and there's no way to do something.

**Comment by smatsson** [comment] 2020-05-22 09:02
Hi @chris03 

The original idea was to only call the callback once to prevent weird issues with e.g. timeouts. Let's say that a client timeout happens and that the client tries again while the first processing is already running. This would then end up with the file being processed multiple times. 

In projects where I have used tusdotnet to do processing we have always just logged when these issues occurred and then handled it manually, e.g. by adding the item manually to a queue or similar. 

I do understand your used case though and would be open to a PR to change this behavior. A caveat here would be that the new behavior would need to be opt-in as to not break existing implementations that rely on the OnUploadCompleteAsync callback only being called once (e.g. by adding some opt-in property to DefaultTusConfiguration -> Events).
